//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class aspnet_ProjectCategories
    {
        public int CategoryId { get; set; }
        public string CategoryName { get; set; }
        public Nullable<int> ProjectId { get; set; }
        public Nullable<int> ParentCategoryId { get; set; }
        public string CategoryAbbreviation { get; set; }
        public Nullable<decimal> CategoryEstimateDuration { get; set; }
    }
}
