//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class aspnet_TimeEntry_Final_20150626
    {
        public int TimeEntryId { get; set; }
        public string ProjectId { get; set; }
        public string ProjectName { get; set; }
        public int CategoryId { get; set; }
        public string RedcapId { get; set; }
        public System.DateTime TimeEntryCreated { get; set; }
        public Nullable<decimal> TimeEntryDuration { get; set; }
        public string TimeEntryDescription { get; set; }
        public Nullable<System.DateTime> TimeEntryDate { get; set; }
        public string TimeEntryCreator { get; set; }
    }
}
