//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class BKP_Journals
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Volume { get; set; }
        public string Issue { get; set; }
        public string Page { get; set; }
        public string DOI { get; set; }
        public string PMID { get; set; }
        public string PMCID { get; set; }
        public string Type { get; set; }
    }
}
