//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class CoAuthorAffils
    {
        public CoAuthorAffils()
        {
            this.PublicationCoAuthorAffil = new HashSet<PublicationCoAuthorAffil>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Type { get; set; }
    
        public virtual ICollection<PublicationCoAuthorAffil> PublicationCoAuthorAffil { get; set; }
    }
}
