//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class D_EMPLOYEE
    {
        public int EMPLOYEE_KEY { get; set; }
        public string EMPLOYEE_NAME { get; set; }
        public string LOGON_ID { get; set; }
        public string EMPLOYEE_TYPE { get; set; }
        public Nullable<int> REDCAP_ID { get; set; }
        public Nullable<int> MEMBER_ID { get; set; }
        public string EMAIL { get; set; }
        public string PHONE { get; set; }
        public Nullable<System.DateTime> CREATE_TS { get; set; }
        public Nullable<System.DateTime> UPDATE_TS { get; set; }
        public Nullable<System.DateTime> EXPIRE_TS { get; set; }
    }
}
