//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dates_bkp
    {
        public int Id { get; set; }
        public string Year { get; set; }
        public string Quarter { get; set; }
        public string Month { get; set; }
        public string Week { get; set; }
        public string Day { get; set; }
        public string QuarterOfYear { get; set; }
        public string MonthOfYear { get; set; }
        public string WeekOfYear { get; set; }
        public string DayOfYear { get; set; }
    }
}
