//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class EthnicGroups
    {
        public EthnicGroups()
        {
            this.Projects = new HashSet<Projects>();
        }
    
        public int Id { get; set; }
        public string GroupName { get; set; }
    
        public virtual ICollection<Projects> Projects { get; set; }
    }
}
