//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class GrantAffils
    {
        public GrantAffils()
        {
            this.ProjectGrants = new HashSet<ProjectGrants>();
            this.PublicationGrants = new HashSet<PublicationGrants>();
        }
    
        public int Id { get; set; }
        public string GrantAffilName { get; set; }
        public Nullable<bool> IsPaperGrant { get; set; }
    
        public virtual ICollection<ProjectGrants> ProjectGrants { get; set; }
        public virtual ICollection<PublicationGrants> PublicationGrants { get; set; }
    }
}
