//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invests_bkp20190520
    {
        public int Id { get; set; }
        public string LastName { get; set; }
        public string FirstName { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public int InvestStatusId { get; set; }
        public string NonUHClient { get; set; }
        public string NonHawaiiClient { get; set; }
        public bool IsApproved { get; set; }
        public string HashValue { get; set; }
        public bool IsPilot { get; set; }
        public string OtherDegree { get; set; }
        public string OtherCommunityPartner { get; set; }
        public string AltEmail { get; set; }
        public string AltPhone { get; set; }
        public string Notes { get; set; }
    }
}
