//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvoiceItem_bkp_20160826
    {
        public int Id { get; set; }
        public int InvoiceId { get; set; }
        public int ClientAgmtId { get; set; }
        public int BiostatId { get; set; }
        public string Desc { get; set; }
        public decimal InvoiceRate { get; set; }
        public decimal InvoiceHr { get; set; }
        public string Creator { get; set; }
        public System.DateTime CreateDate { get; set; }
    }
}
