//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invoice_bkp20200812
    {
        public int Id { get; set; }
        public int CollabCtrId { get; set; }
        public System.DateTime InvoiceDate { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public Nullable<decimal> SubTotal { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public Nullable<System.DateTime> PaymentRcvdDate { get; set; }
        public Nullable<decimal> PaymentRcvdAmount { get; set; }
        public string FileName { get; set; }
        public byte[] FileUpload { get; set; }
        public string Comments { get; set; }
        public string Creator { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string InvoiceId { get; set; }
    }
}
