//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class JabsomAffils
    {
        public JabsomAffils()
        {
            this.MajorHospitals = new HashSet<MajorHospitals>();
            this.Invests = new HashSet<Invests>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Type { get; set; }
        public string PrevName { get; set; }
    
        public virtual ICollection<MajorHospitals> MajorHospitals { get; set; }
        public virtual ICollection<Invests> Invests { get; set; }
    }
}
