//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class MajorHospitals
    {
        public MajorHospitals()
        {
            this.MajorHospitals1 = new HashSet<MajorHospitals>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> ParentId { get; set; }
        public int JabsomAffilId { get; set; }
    
        public virtual JabsomAffils JabsomAffils { get; set; }
        public virtual ICollection<MajorHospitals> MajorHospitals1 { get; set; }
        public virtual MajorHospitals MajorHospitals2 { get; set; }
    }
}
