//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class Project2Biostat
    {
        public int Id { get; set; }
        public int ProjectId { get; set; }
        public int BiostatId { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public string Creator { get; set; }
        public System.DateTime CreationDate { get; set; }
    
        public virtual BioStats BioStats { get; set; }
        public virtual Project2 Project2 { get; set; }
    }
}
