//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class RMATRIX_Monthly
    {
        public int participant_id { get; set; }
        public string rfr_date { get; set; }
        public string name_lastname { get; set; }
        public string name_firstname { get; set; }
        public string prior_request { get; set; }
        public string degree___1 { get; set; }
        public string degree___2 { get; set; }
        public string degree___3 { get; set; }
        public string degree___4 { get; set; }
        public string degree___5 { get; set; }
        public string degree___6 { get; set; }
        public string degree___7 { get; set; }
        public string degree___8 { get; set; }
        public string degree___9 { get; set; }
        public string degree___10 { get; set; }
        public string degree___11 { get; set; }
        public string other_degree { get; set; }
        public string invest_status { get; set; }
        public string email { get; set; }
        public string phone { get; set; }
        public string specify_degree { get; set; }
        public string affiliations___1 { get; set; }
        public string affiliations___2 { get; set; }
        public string affiliations___3 { get; set; }
        public string affiliations___4 { get; set; }
        public string affiliations___5 { get; set; }
        public string affiliations___6 { get; set; }
        public string affiliations___7 { get; set; }
        public string affiliations___8 { get; set; }
        public string affiliations___9 { get; set; }
        public string manoa___1 { get; set; }
        public string manoa___2 { get; set; }
        public string manoa___3 { get; set; }
        public string other_affiliation { get; set; }
        public string uh_mano_college___1 { get; set; }
        public string uh_mano_college___2 { get; set; }
        public string uh_mano_college___3 { get; set; }
        public string uh_mano_college___4 { get; set; }
        public string uh_mano_college___5 { get; set; }
        public string uh_mano_college___6 { get; set; }
        public string uh_manoa_school___1 { get; set; }
        public string uh_manoa_school___2 { get; set; }
        public string uh_manoa_school___3 { get; set; }
        public string uh_manoa_school___4 { get; set; }
        public string uh_manoa_school___5 { get; set; }
        public string uh_manoa_school___6 { get; set; }
        public string uh_manoa_school___7 { get; set; }
        public string uh_manoa_school___8 { get; set; }
        public string uh_manoa_school___9 { get; set; }
        public string uh_manoa_school___10 { get; set; }
        public string uh_manoa_school___11 { get; set; }
        public string uh_manoa_school___12 { get; set; }
        public string uh_manoa_school___13 { get; set; }
        public string other_deptschool { get; set; }
        public string jabsom_dept___1 { get; set; }
        public string jabsom_dept___2 { get; set; }
        public string jabsom_dept___3 { get; set; }
        public string jabsom_dept___4 { get; set; }
        public string jabsom_dept___5 { get; set; }
        public string jabsom_dept___6 { get; set; }
        public string jabsom_dept___7 { get; set; }
        public string jabsom_dept___8 { get; set; }
        public string jabsom_dept___9 { get; set; }
        public string jabsom_dept___10 { get; set; }
        public string jabsom_dept___11 { get; set; }
        public string jabsom_dept___12 { get; set; }
        public string jabsom_dept___13 { get; set; }
        public string jabsom_dept___14 { get; set; }
        public string jabsom_dept___15 { get; set; }
        public string jabsom_dept___16 { get; set; }
        public string jabsom_other { get; set; }
        public string uh_hilo { get; set; }
        public string west_oahu { get; set; }
        public string community_college { get; set; }
        public string cmty_partners___1 { get; set; }
        public string cmty_partners___2 { get; set; }
        public string cmty_partners___3 { get; set; }
        public string cmty_partners___4 { get; set; }
        public string cmty_partners___5 { get; set; }
        public string cmty_partner_other { get; set; }
        public string hospitals___1 { get; set; }
        public string hospitals___2 { get; set; }
        public string hospitals___3 { get; set; }
        public string hospitals___4 { get; set; }
        public string hospitals___5 { get; set; }
        public string hospitals___6 { get; set; }
        public string major_hph___1 { get; set; }
        public string major_hph___2 { get; set; }
        public string major_hph___3 { get; set; }
        public string other_university_college { get; set; }
        public string other_institution { get; set; }
        public string project_title { get; set; }
        public string project_summary { get; set; }
        public string upload { get; set; }
        public string health_initiative___1 { get; set; }
        public string health_initiative___2 { get; set; }
        public string health_initiative___3 { get; set; }
        public string health_initiative___4 { get; set; }
        public string health_initiative___5 { get; set; }
        public string health_initiative___6 { get; set; }
        public string health_initiative___7 { get; set; }
        public string ethnic___1 { get; set; }
        public string ethnic___2 { get; set; }
        public string ethnic___3 { get; set; }
        public string ethnic___4 { get; set; }
        public string ethnic___5 { get; set; }
        public string ethnic___6 { get; set; }
        public string ethnic_other { get; set; }
        public string grants___1 { get; set; }
        public string grants___2 { get; set; }
        public string grants___3 { get; set; }
        public string grants___4 { get; set; }
        public string grants___5 { get; set; }
        public string grants___6 { get; set; }
        public string grants___7 { get; set; }
        public string grants___8 { get; set; }
        public string grants___9 { get; set; }
        public string grants_other { get; set; }
        public string grant_pilot { get; set; }
        public string grant_pilot_y___1 { get; set; }
        public string grant_pilot_y___2 { get; set; }
        public string grant_pilot_y___3 { get; set; }
        public string grant_pilot_y___4 { get; set; }
        public string grant_pilot_y___5 { get; set; }
        public string grant_pilot_y___6 { get; set; }
        public string grant_pilot_y___7 { get; set; }
        public string grant_pilot_other { get; set; }
        public string service_request___1 { get; set; }
        public string service_request___2 { get; set; }
        public string service_request___3 { get; set; }
        public string service_request___4 { get; set; }
        public string service_request___5 { get; set; }
        public string service_request___6 { get; set; }
        public string service_request___7 { get; set; }
        public string service_request___8 { get; set; }
        public string service_request___9 { get; set; }
        public string service_request___10 { get; set; }
        public string service_other { get; set; }
        public string goals { get; set; }
    }
}
