//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class S_Extra_Grant
    {
        public int Id { get; set; }
        public string PIName { get; set; }
        public string PIEmail { get; set; }
        public string Collab { get; set; }
        public string HealthInit { get; set; }
        public string NativeHawaiian { get; set; }
        public string GrantTitle { get; set; }
        public string GrantCategory { get; set; }
        public string GrantType { get; set; }
        public string PgmAnn { get; set; }
        public string FundAgcy { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<decimal> FirstYrAmt { get; set; }
        public Nullable<decimal> TotalAmt { get; set; }
        public string MyGrantNum { get; set; }
        public Nullable<System.DateTime> SubDeadline { get; set; }
        public string GrantStatus { get; set; }
        public Nullable<System.DateTime> SubDate { get; set; }
        public string FundStatus { get; set; }
        public string Followup { get; set; }
        public Nullable<System.DateTime> InitContactDate { get; set; }
        public string Biostats { get; set; }
        public string PctAndFee { get; set; }
        public Nullable<int> ProjectId { get; set; }
        public Nullable<bool> IsProposal { get; set; }
        public Nullable<bool> IsSupport { get; set; }
        public bool IsInternal { get; set; }
        public string Comment { get; set; }
    }
}
