//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class S_PROJECT
    {
        public string REDCAP_ID { get; set; }
        public string PROJECT_TITLE { get; set; }
        public string PI_FIRSTNAME { get; set; }
        public string PI_LASTNAME { get; set; }
        public string PROJECT_SUMMARY { get; set; }
        public string COMMENTS { get; set; }
        public string LEAD_BIOSTAT { get; set; }
        public string MEMBER { get; set; }
        public Nullable<System.DateTime> DEADLINE { get; set; }
        public Nullable<bool> IS_ACTIVE { get; set; }
        public Nullable<System.DateTime> INITIAL_DATE { get; set; }
        public Nullable<System.DateTime> UPDATE_DATE { get; set; }
        public Nullable<System.DateTime> COMPLETE_DATE { get; set; }
        public Nullable<System.DateTime> LOAD_DATE { get; set; }
        public string FILE_NAME { get; set; }
    }
}
