//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwTimeEntry
    {
        public int ProjectId { get; set; }
        public int biostatid { get; set; }
        public string BiostatType { get; set; }
        public Nullable<decimal> phd { get; set; }
        public Nullable<decimal> ms { get; set; }
    }
}
